# Data Deuce: Source Profiling

## About the Source

My plan is to use [TennisMyLife's database](https://stats.tennismylife.org/tennis-match-database) available via API.

## Libraries

In [1]:
import re

import pandas as pd
import requests

## First Look

### Raw Source

In [2]:
API_URL = "https://stats.tennismylife.org/api/data-files"

response = requests.get(API_URL).json()

### Filtering Relevant Files

ATP (`<year>.csv`) and WTA (`<year>_wta.csv`) only — see #14/#17 for why Challenger, Qualifying, amateur, backup, and ongoing files are excluded.

In [3]:
pattern = re.compile(r"^\d{4}(_wta)?\.csv$")

matches = [item["name"] for item in response["files"] if pattern.match(item["name"])]
matches

['1967.csv',
 '1968.csv',
 '1969.csv',
 '1970.csv',
 '1971.csv',
 '1972.csv',
 '1973.csv',
 '1974.csv',
 '1975.csv',
 '1976.csv',
 '1977.csv',
 '1978.csv',
 '1979.csv',
 '1980.csv',
 '1981.csv',
 '1982.csv',
 '1983.csv',
 '1984.csv',
 '1985.csv',
 '1986.csv',
 '1987.csv',
 '1988.csv',
 '1989.csv',
 '1990.csv',
 '1990_wta.csv',
 '1991.csv',
 '1991_wta.csv',
 '1992.csv',
 '1992_wta.csv',
 '1993.csv',
 '1993_wta.csv',
 '1994.csv',
 '1994_wta.csv',
 '1995.csv',
 '1995_wta.csv',
 '1996.csv',
 '1996_wta.csv',
 '1997.csv',
 '1997_wta.csv',
 '1998.csv',
 '1998_wta.csv',
 '1999.csv',
 '1999_wta.csv',
 '2000.csv',
 '2000_wta.csv',
 '2001.csv',
 '2001_wta.csv',
 '2002.csv',
 '2002_wta.csv',
 '2003.csv',
 '2003_wta.csv',
 '2004.csv',
 '2004_wta.csv',
 '2005.csv',
 '2005_wta.csv',
 '2006.csv',
 '2006_wta.csv',
 '2007.csv',
 '2007_wta.csv',
 '2008.csv',
 '2008_wta.csv',
 '2009.csv',
 '2009_wta.csv',
 '2010.csv',
 '2010_wta.csv',
 '2011.csv',
 '2011_wta.csv',
 '2012.csv',
 '2012_wta.csv',
 '2013.csv',
 '2013_wta.csv',
 '2014.csv',
 '2014_wta.csv',
 '2015.csv',
 '2015_wta.csv',
 '2016.csv',
 '2016_wta.csv',
 '2017.csv',
 '2017_wta.csv',
 '2018.csv',
 '2018_wta.csv',
 '2019.csv',
 '2019_wta.csv',
 '2020.csv',
 '2020_wta.csv',
 '2021.csv',
 '2021_wta.csv',
 '2022.csv',
 '2022_wta.csv',
 '2023.csv',
 '2023_wta.csv',
 '2024.csv',
 '2024_wta.csv',
 '2025.csv',
 '2025_wta.csv',
 '2026.csv',
 '2026_wta.csv']

In [4]:
atp_files = [
    item
    for item in response["files"]
    if item["name"] in matches and not item["name"].endswith("_wta.csv")
]
wta_files = [
    item
    for item in response["files"]
    if item["name"] in matches and item["name"].endswith("_wta.csv")
]

atp_by_name = {item["name"]: item["url"] for item in atp_files}
wta_by_name = {item["name"]: item["url"] for item in wta_files}

print(f"ATP files: {len(atp_files)}, WTA files: {len(wta_files)}")

ATP files: 60, WTA files: 37

### Basic Exploration

I'm taking the files from 2025 to understand the data, since it's fairly recent and covers a full year.

In [5]:
atp_2025 = pd.read_csv(atp_by_name["2025.csv"])
wta_2025 = pd.read_csv(wta_by_name["2025_wta.csv"])

In [6]:
print("ATP 2025:", atp_2025.shape)
print("WTA 2025:", wta_2025.shape)

ATP 2025: (2944, 50)
WTA 2025: (2622, 50)

In [7]:
atp_2025.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,indoor,tourney_date,match_num,winner_id,winner_seed,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2025-9900,United Cup,Hard,18.0,A,O,20241229,1.0,CD85,NaN,...,2.0,3.0,4.0,42.0,24.0,14.0,4.0,7.0,2.0,7.0
1,2025-9900,United Cup,Hard,18.0,A,O,20241229,2.0,Z371,NaN,...,0.0,3.0,2.0,35.0,22.0,13.0,3.0,7.0,1.0,5.0
2,2025-9900,United Cup,Hard,18.0,A,O,20241229,3.0,TE51,NaN,...,3.0,2.0,3.0,92.0,70.0,48.0,9.0,14.0,6.0,9.0
3,2025-9900,United Cup,Hard,18.0,A,O,20241229,4.0,CG80,NaN,...,10.0,13.0,3.0,90.0,67.0,43.0,11.0,13.0,8.0,12.0
4,2025-9900,United Cup,Hard,18.0,A,O,20241229,5.0,HH26,NaN,...,1.0,10.0,1.0,56.0,34.0,27.0,10.0,10.0,1.0,4.0

In [8]:
wta_2025.head()

,tourney_id,tourney_name,surface,draw_size,tourney_level,indoor,tourney_date,match_num,winner_id,winner_seed,...,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
0,2025-2084,United Cup,Hard,18,A,NaN,20241230,1,211107,NaN,...,1.0,1.0,4.0,51.0,24.0,13.0,10.0,8.0,5.0,10.0
1,2025-2084,United Cup,Hard,18,A,NaN,20241230,2,211107,NaN,...,2.0,1.0,4.0,51.0,33.0,22.0,4.0,8.0,7.0,11.0
2,2025-2084,United Cup,Hard,18,A,NaN,20241230,3,206408,NaN,...,3.0,1.0,5.0,68.0,45.0,26.0,6.0,9.0,12.0,17.0
3,2025-2084,United Cup,Hard,18,A,NaN,20241230,4,214386,NaN,...,9.0,2.0,0.0,70.0,55.0,30.0,8.0,12.0,6.0,12.0
4,2025-2084,United Cup,Hard,18,A,NaN,20241230,5,201696,NaN,...,7.0,4.0,7.0,103.0,69.0,41.0,14.0,13.0,13.0,18.0

### Types and Nulls

Checking dtypes and missing values — worth comparing ATP vs. WTA here given the site's own disclaimer about WTA data reliability.

In [9]:
atp_2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 2944 entries, 0 to 2943
Data columns (total 50 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          2944 non-null   str
 1   tourney_name        2944 non-null   str
 2   surface             2944 non-null   str
 3   draw_size           2928 non-null   float64
 4   tourney_level       2944 non-null   str
 5   indoor              2708 non-null   str
 6   tourney_date        2944 non-null   int64
 7   match_num           2455 non-null   float64
 8   winner_id           2944 non-null   str
 9   winner_seed         1200 non-null   float64
 10  winner_entry        305 non-null    str
 11  winner_name         2944 non-null   str
 12  winner_hand         2926 non-null   str
 13  winner_ht           2916 non-null   float64
 14  winner_ioc          2942 non-null   str
 15  winner_age          2942 non-null   float64
 16  winner_rank         2931 non-null   float64
 17  winner_rank_points  2931 non-null   float64
 18  loser_id            2944 non-null   str
 19  loser_seed          700 non-null    float64
 20  loser_entry         480 non-null    str
 21  loser_name          2944 non-null   str
 22  loser_hand          2894 non-null   str
 23  loser_ht            2882 non-null   float64
 24  loser_ioc           2943 non-null   str
 25  loser_age           2941 non-null   float64
 26  loser_rank          2886 non-null   float64
 27  loser_rank_points   2886 non-null   float64
 28  score               2944 non-null   str
 29  best_of             2944 non-null   int64
 30  round               2944 non-null   str
 31  minutes             2753 non-null   float64
 32  w_ace               2751 non-null   float64
 33  w_df                2751 non-null   float64
 34  w_svpt              2751 non-null   float64
 35  w_1stIn             2751 non-null   float64
 36  w_1stWon            2751 non-null   float64
 37  w_2ndWon            2751 non-null   float64
 38  w_SvGms             2751 non-null   float64
 39  w_bpSaved           2751 non-null   float64
 40  w_bpFaced           2751 non-null   float64
 41  l_ace               2751 non-null   float64
 42  l_df                2751 non-null   float64
 43  l_svpt              2751 non-null   float64
 44  l_1stIn             2751 non-null   float64
 45  l_1stWon            2751 non-null   float64
 46  l_2ndWon            2751 non-null   float64
 47  l_SvGms             2751 non-null   float64
 48  l_bpSaved           2751 non-null   float64
 49  l_bpFaced           2751 non-null   float64
dtypes: float64(31), int64(2), str(17)
memory usage: 1.1 MB

In [10]:
wta_2025.info()

<class 'pandas.DataFrame'>
RangeIndex: 2622 entries, 0 to 2621
Data columns (total 50 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   tourney_id          2622 non-null   str
 1   tourney_name        2622 non-null   str
 2   surface             2622 non-null   str
 3   draw_size           2622 non-null   int64
 4   tourney_level       2622 non-null   str
 5   indoor              0 non-null      float64
 6   tourney_date        2622 non-null   int64
 7   match_num           2622 non-null   int64
 8   winner_id           2622 non-null   int64
 9   winner_seed         1011 non-null   float64
 10  winner_entry        423 non-null    str
 11  winner_name         2622 non-null   str
 12  winner_hand         2557 non-null   str
 13  winner_ht           1874 non-null   float64
 14  winner_ioc          2622 non-null   str
 15  winner_age          2617 non-null   float64
 16  winner_rank         2616 non-null   float64
 17  winner_rank_points  2616 non-null   float64
 18  loser_id            2622 non-null   int64
 19  loser_seed          660 non-null    str
 20  loser_entry         613 non-null    str
 21  loser_name          2622 non-null   str
 22  loser_hand          2496 non-null   str
 23  loser_ht            1704 non-null   float64
 24  loser_ioc           2621 non-null   str
 25  loser_age           2610 non-null   float64
 26  loser_rank          2615 non-null   float64
 27  loser_rank_points   2615 non-null   float64
 28  score               2622 non-null   str
 29  best_of             2622 non-null   int64
 30  round               2622 non-null   str
 31  minutes             2356 non-null   float64
 32  w_ace               2514 non-null   float64
 33  w_df                2514 non-null   float64
 34  w_svpt              2514 non-null   float64
 35  w_1stIn             2514 non-null   float64
 36  w_1stWon            2514 non-null   float64
 37  w_2ndWon            2514 non-null   float64
 38  w_SvGms             2512 non-null   float64
 39  w_bpSaved           2514 non-null   float64
 40  w_bpFaced           2514 non-null   float64
 41  l_ace               2514 non-null   float64
 42  l_df                2514 non-null   float64
 43  l_svpt              2514 non-null   float64
 44  l_1stIn             2514 non-null   float64
 45  l_1stWon            2514 non-null   float64
 46  l_2ndWon            2514 non-null   float64
 47  l_SvGms             2512 non-null   float64
 48  l_bpSaved           2514 non-null   float64
 49  l_bpFaced           2514 non-null   float64
dtypes: float64(29), int64(6), str(15)
memory usage: 1.0 MB

In [11]:
null_pct = pd.DataFrame(
    {
        "atp_null_pct": atp_2025.isnull().mean() * 100,
        "wta_null_pct": wta_2025.isnull().mean() * 100,
    }
)
null_pct

                    atp_null_pct  wta_null_pct
tourney_id              0.000000      0.000000
tourney_name            0.000000      0.000000
surface                 0.000000      0.000000
draw_size               0.543478      0.000000
tourney_level           0.000000      0.000000
indoor                  8.016304    100.000000
tourney_date            0.000000      0.000000
match_num              16.610054      0.000000
winner_id               0.000000      0.000000
winner_seed            59.239130     61.441648
winner_entry           89.639946     83.867277
winner_name             0.000000      0.000000
winner_hand             0.611413      2.479024
winner_ht               0.951087     28.527841
winner_ioc              0.067935      0.000000
winner_age              0.067935      0.190694
winner_rank             0.441576      0.228833
winner_rank_points      0.441576      0.228833
loser_id                0.000000      0.000000
loser_seed             76.222826     74.828375
loser_entry            83.695652     76.620900
loser_name              0.000000      0.000000
loser_hand              1.698370      4.805492
loser_ht                2.105978     35.011442
loser_ioc               0.033967      0.038139
loser_age               0.101902      0.457666
loser_rank              1.970109      0.266972
loser_rank_points       1.970109      0.266972
score                   0.000000      0.000000
best_of                 0.000000      0.000000
round                   0.000000      0.000000
minutes                 6.487772     10.144928
w_ace                   6.555707      4.118993
w_df                    6.555707      4.118993
w_svpt                  6.555707      4.118993
w_1stIn                 6.555707      4.118993
w_1stWon                6.555707      4.118993
w_2ndWon                6.555707      4.118993
w_SvGms                 6.555707      4.195271
w_bpSaved               6.555707      4.118993
w_bpFaced               6.555707      4.118993
l_ace                   6.555707      4.118993
l_df                    6.555707      4.118993
l_svpt                  6.555707      4.118993
l_1stIn                 6.555707      4.118993
l_1stWon                6.555707      4.118993
l_2ndWon                6.555707      4.118993
l_SvGms                 6.555707      4.195271
l_bpSaved               6.555707      4.118993
l_bpFaced               6.555707      4.118993

## Deep Dive

### ATP

#### 1. What's the available date range?

My takeaways:
- `2024-12-29` to `2025-12-22` — not a clean calendar year, since United Cup (pre-season) starts in late December of the prior year.

In [12]:
atp_2025_dates = pd.to_datetime(atp_2025["tourney_date"], format="%Y%m%d")
atp_2025_dates.min(), atp_2025_dates.max()

(Timestamp('2024-12-29 00:00:00'), Timestamp('2025-12-22 00:00:00'))

#### 2. Is there a timestamp? If so, what timezone?

My takeaways:
- No timestamp, no timezone — only `tourney_date` (`int64`, `YYYYMMDD`), tz-naive.

In [13]:
date_like_cols = atp_2025.filter(regex="date|time|tz", axis=1).columns.tolist()
date_like_cols, atp_2025["tourney_date"].dtype, atp_2025_dates.dt.tz

(['tourney_date'], dtype('int64'), None)

#### 3. What does `tourney_date` mean, and what's the distribution of values?

My takeaways:
- `tourney_date` = tournament-level anchor, constant per `tourney_id` — not a per-match date.
- Confirmed as **start of tournament week** against Australian Open 2025 (`20250113`, the real Monday).
- No per-match date field exists anywhere — this source only gives week-level granularity.
- Exceptions: **WTA Finals** (round-robin) and **BJK Cup** (team event) span multiple dates per `tourney_id`.

In [14]:
atp_2025.groupby("tourney_id")["tourney_date"].nunique().value_counts()

tourney_date
1    197
Name: count, dtype: int64

#### 4. Does match count per tournament match `draw_size`?

My takeaways:
- 110/197 tourneys mismatched — mostly round-robin (ATP/Next Gen Finals), team/exhibition formats (Laver Cup, United Cup) where `draw_size` isn't bracket slots, and Davis Cup split into one `tourney_id` per tie-match (`draw_size=4`, single match logged).
- Dubai's lone non-format mismatch traced to a duplicate row — see question 6.

In [15]:
atp_match_counts = atp_2025.groupby("tourney_id").agg(
    tourney_name=("tourney_name", "first"),
    draw_size=("draw_size", "first"),
    actual_matches=("match_num", "size"),
)
atp_match_counts["expected_matches"] = atp_match_counts["draw_size"] - 1
atp_match_counts["diff"] = (
    atp_match_counts["actual_matches"] - atp_match_counts["expected_matches"]
)

atp_match_counts[atp_match_counts["diff"] != 0]

,tourney_name,draw_size,actual_matches,expected_matches,diff
tourney_id,,,,,
2025-495,Dubai,32.0,32,31.0,1.0
2025-605,ATP Finals,8.0,15,7.0,8.0
2025-7696,Next Gen ATP Finals,8.0,15,7.0,8.0
2025-9210,Laver Cup,2.0,9,1.0,8.0
2025-9900,United Cup,18.0,25,17.0,8.0
...,...,...,...,...,...
2025-M-DC-2025-WG2-R1-TOG-EGY-02,Davis Cup WG2 R1: TOG vs EGY,4.0,1,3.0,-2.0
2025-M-DC-2025-WG2-R1-TOG-EGY-04,Davis Cup WG2 R1: TOG vs EGY,4.0,1,3.0,-2.0
2025-M-DC-2025-WG2-R1-UKR-DOM-01,Davis Cup WG2 R1: UKR vs DOM,4.0,1,3.0,-2.0
2025-M-DC-2025-WG2-R1-UKR-DOM-02,Davis Cup WG2 R1: UKR vs DOM,4.0,1,3.0,-2.0
2025-M-DC-2025-WG2-R1-UKR-DOM-04,Davis Cup WG2 R1: UKR vs DOM,4.0,1,3.0,-2.0

In [16]:
dubai = atp_2025[atp_2025["tourney_id"] == "2025-495"]
dubai["round"].value_counts()

round
R32    17
R16     8
QF      4
SF      2
F       1
Name: count, dtype: int64

In [17]:
dubai[dubai.duplicated(subset=["winner_name", "loser_name", "round"], keep=False)][
    ["round", "match_num", "winner_name", "loser_name", "score"]
]

    round  match_num winner_name        loser_name        score
633   R32       10.0  Luca Nardi  Marton Fucsovics  1-6 6-2 6-3
634   R32       11.0  Luca Nardi  Marton Fucsovics  1-6 6-2 6-3

In [18]:
dubai[dubai["score"].str.contains(r"[^0-9\-\s()]", na=False)][
    ["round", "match_num", "winner_name", "loser_name", "score"]
]

    round  match_num            winner_name       loser_name    score
628   R32        5.0  Christopher O'Connell  Grigor Dimitrov  6-0 RET

#### 5. How do non-standard outcomes (retirement, walkover, default) show up in `score`?

My takeaways:
- 102 distinct patterns, all either RET (~100, partial set score + retirement) or W/O (22, clean). No DEF or ABD found in 2025.

In [19]:
atp_2025[atp_2025["score"].str.contains(r"[^0-9\-\s()]", na=False)][
    "score"
].value_counts()

score
W/O                   22
7-5 RET                4
6-3 RET                3
6-4 3-1 RET            3
4-1 RET                2
                      ..
6-7(8) 6-1 4-1 RET     1
7-6(1) RET             1
3-6 6-3 4-1 RET        1
7-6(4) 3-1 RET         1
4-6 6-0 RET            1
Name: count, Length: 102, dtype: int64

#### 6. Are there duplicate match rows?

My takeaways:
- 0 full-row duplicates; 1 business-key duplicate (`tourney_id` + players + `round`) — the Nardi/Fucsovics case from Dubai (question 4), isolated, not systemic.

In [20]:
atp_2025.duplicated().sum()

np.int64(0)

In [21]:
atp_2025.duplicated(subset=["tourney_id", "winner_name", "loser_name", "round"]).sum()

np.int64(1)

#### 7. Of the tournaments that don't match `draw_size`, which aren't explained by a known special format (Finals/Cup)?

In [22]:
atp_mismatches = atp_match_counts[atp_match_counts["diff"] != 0]
known_format = atp_mismatches["tourney_name"].str.contains(
    "Finals|Cup", case=False, na=False
)

atp_mismatches[~known_format]

           tourney_name  draw_size  actual_matches  expected_matches  diff
tourney_id
2025-495          Dubai       32.0              32              31.0   1.0

#### 8. How do bye cases show up in the data?

In [23]:
(
    atp_2025["round"].unique(),
    atp_2025[atp_2025["score"].str.contains("bye", case=False, na=False)],
)

(<StringArray>
 ['RR', 'F', 'R32', 'R16', 'QF', 'SF', 'R128', 'R64']
 Length: 8, dtype: str,
 Empty DataFrame
 Columns: [tourney_id, tourney_name, surface, draw_size, tourney_level, indoor, tourney_date, match_num, winner_id, winner_seed, winner_entry, winner_name, winner_hand, winner_ht, winner_ioc, winner_age, winner_rank, winner_rank_points, loser_id, loser_seed, loser_entry, loser_name, loser_hand, loser_ht, loser_ioc, loser_age, loser_rank, loser_rank_points, score, best_of, round, minutes, w_ace, w_df, w_svpt, w_1stIn, w_1stWon, w_2ndWon, w_SvGms, w_bpSaved, w_bpFaced, l_ace, l_df, l_svpt, l_1stIn, l_1stWon, l_2ndWon, l_SvGms, l_bpSaved, l_bpFaced]
 Index: []

 [0 rows x 50 columns])

#### 9. Is the `player_id` ↔ name relationship 1:1?

My takeaways:
- 0 violations, both directions — clean.

In [24]:
atp_players = pd.concat(
    [
        atp_2025[["winner_id", "winner_name"]].rename(
            columns={"winner_id": "player_id", "winner_name": "player_name"}
        ),
        atp_2025[["loser_id", "loser_name"]].rename(
            columns={"loser_id": "player_id", "loser_name": "player_name"}
        ),
    ]
).drop_duplicates()

atp_id_violations = atp_players.groupby("player_id")["player_name"].nunique()
atp_id_violations[atp_id_violations > 1]

Series([], Name: player_name, dtype: int64)

In [25]:
atp_name_violations = atp_players.groupby("player_name")["player_id"].nunique()
atp_name_violations[atp_name_violations > 1]

Series([], Name: player_id, dtype: int64)

#### 10. Are the serve-stat columns internally consistent (`1stIn <= svpt`, `1stWon <= 1stIn`, `1stWon + 2ndWon <= svpt`)?

My takeaways:
- 2 violations, both **Davis Cup** matches. Norrie vs. Pieczkowski (POL vs GBR): `w_1stIn=62` exactly equals `l_svpt=62` — looks like a value misassigned between winner/loser, not just a rounding slip. Consistent with Davis Cup's already-shaky pipeline in this source (question 4's fragmented `tourney_id`).

In [26]:
atp_violations = atp_2025[
    (atp_2025["w_1stIn"] > atp_2025["w_svpt"])
    | (atp_2025["w_1stWon"] > atp_2025["w_1stIn"])
    | (atp_2025["w_1stWon"] + atp_2025["w_2ndWon"] > atp_2025["w_svpt"])
    | (atp_2025["l_1stIn"] > atp_2025["l_svpt"])
    | (atp_2025["l_1stWon"] > atp_2025["l_1stIn"])
    | (atp_2025["l_1stWon"] + atp_2025["l_2ndWon"] > atp_2025["l_svpt"])
]

atp_violations[
    [
        "tourney_name",
        "round",
        "winner_name",
        "loser_name",
        "w_svpt",
        "w_1stIn",
        "w_1stWon",
        "w_2ndWon",
        "l_svpt",
        "l_1stIn",
        "l_1stWon",
        "l_2ndWon",
    ]
]

,tourney_name,round,winner_name,loser_name,w_svpt,w_1stIn,w_1stWon,w_2ndWon,l_svpt,l_1stIn,l_1stWon,l_2ndWon
2338,Davis Cup WG1 R1: POL vs GBR,RR,Cameron Norrie,Olaf Pieczkowski,42.0,62.0,27.0,8.0,62.0,37.0,40.0,2.0
2344,Davis Cup WG1 R1: SUI vs IND,RR,Sumit Nagal,Henry Bernet,45.0,48.0,33.0,4.0,41.0,27.0,18.0,2.0

#### 11. Are break points saved always ≤ break points faced?

My takeaways:
- 4 violations, **all Davis Cup**. Two are the same rows flagged in question 10 (Norrie/Pieczkowski, Nagal/Bernet) — those rows are broadly corrupted, not a single bad column. Two new ones (Kwon/Bublik, Barrios Vera/Knaff) only show up here, not in question 10.
- Reinforces: Davis Cup rows in this source need extra scrutiny across the board, not just one stat family.

In [27]:
atp_bp_violations = atp_2025[
    (atp_2025["w_bpSaved"] > atp_2025["w_bpFaced"])
    | (atp_2025["l_bpSaved"] > atp_2025["l_bpFaced"])
]

atp_bp_violations[
    [
        "tourney_name",
        "round",
        "winner_name",
        "loser_name",
        "w_bpSaved",
        "w_bpFaced",
        "l_bpSaved",
        "l_bpFaced",
    ]
]

,tourney_name,round,winner_name,loser_name,w_bpSaved,w_bpFaced,l_bpSaved,l_bpFaced
2321,Davis Cup WG1 R1: KOR vs KAZ,RR,Soonwoo Kwon,Alexander Bublik,4.0,1.0,0.0,4.0
2338,Davis Cup WG1 R1: POL vs GBR,RR,Cameron Norrie,Olaf Pieczkowski,2.0,0.0,0.0,10.0
2344,Davis Cup WG1 R1: SUI vs IND,RR,Sumit Nagal,Henry Bernet,4.0,1.0,0.0,8.0
2353,Davis Cup WG1 R1: CHI vs LUX,RR,Tomas Barrios Vera,Alex Knaff,2.0,2.0,13.0,2.0

#### 12. Do categorical columns match the values documented in the TML-Database dictionary?

Dictionary source: the site’s own [tournament-database page](https://stats.tennismylife.org/tennis-match-database), pasted in full by Ana after my first WebFetch summary silently dropped the `indoor` row — cross-checked against the [Tennismylife/TML-Database README](https://github.com/Tennismylife/TML-Database), which agrees on every field.

Caveat on `entry`: the site only gives examples ("e.g., Q, WC"), not an exhaustive list — unlike GitHub, which states `Q, WC, LL, SE` as complete. So an entry-code "violation" below isn’t necessarily a data error; it could be a legitimate code neither source bothered to document (e.g. "PR" for protected ranking).

My takeaways:
- `indoor`: documented as `Yes/No`, but the real values are `I`/`O` — almost certainly Indoor/Outdoor codes, not a boolean. Needs a mapping decision in the raw/bronze schema (e.g. `I` → true), not a straight boolean cast.
- `round`: `RR` (round robin) undocumented but expected — already known from question 3.
- `tourney_level`: actual values are `250`, `500`, `M` — the source uses ATP’s real tier naming, not the documented `G/A/D/F` scheme. Documentation is stale here, not the data.
- `entry`: `PR` (protected ranking), `ALT` (alternate) — real, legitimate codes just not documented (consistent with the site’s own "e.g." caveat). `NG` (loser_entry, 3 rows, all ATP 250 grass events) — meaning not confirmed; scores are normal (no RET/WO), so not a withdrawal marker.
- `draw_size`: extra values (18, 28, 48, 56, 96, 2) all trace back to known non-standard formats already explored — United Cup, 28-draws, Madrid-style combined events, Laver Cup.

In [28]:
expected = {
    "surface": {"Hard", "Clay", "Grass", "Carpet"},
    "draw_size": {128, 64, 32, 16, 8, 4},
    "tourney_level": {"G", "A", "D", "F"},
    "indoor": {"Yes", "No"},
    "winner_entry": {"Q", "WC", "LL", "SE"},
    "loser_entry": {"Q", "WC", "LL", "SE"},
    "winner_hand": {"R", "L"},
    "loser_hand": {"R", "L"},
    "round": {"R128", "R64", "R32", "R16", "QF", "SF", "F"},
    "best_of": {3, 5},
}

atp_dict_violations = {
    col: sorted(set(atp_2025[col].dropna().unique()) - allowed, key=str)
    for col, allowed in expected.items()
}
{col: vals for col, vals in atp_dict_violations.items() if vals}

{'draw_size': [np.float64(18.0),
  np.float64(2.0),
  np.float64(28.0),
  np.float64(48.0),
  np.float64(56.0),
  np.float64(96.0)],
 'tourney_level': ['250', '500', 'M'],
 'indoor': ['I', 'O'],
 'winner_entry': ['PR'],
 'loser_entry': ['ALT', 'NG', 'PR'],
 'round': ['RR']}

### WTA

#### 1. What's the available date range?

My takeaways:
- `2024-12-30` to `2025-11-14` — also starts in prior December (United Cup); ends earlier than ATP since the WTA season wraps up before the men's Davis Cup Finals.

In [29]:
wta_2025_dates = pd.to_datetime(wta_2025["tourney_date"], format="%Y%m%d")
wta_2025_dates.min(), wta_2025_dates.max()

(Timestamp('2024-12-30 00:00:00'), Timestamp('2025-11-14 00:00:00'))

#### 2. Is there a timestamp? If so, what timezone?

My takeaways:
- Same as ATP: no timestamp, no timezone — only `tourney_date` (`int64`, `YYYYMMDD`), tz-naive.

In [30]:
date_like_cols = wta_2025.filter(regex="date|time|tz", axis=1).columns.tolist()
date_like_cols, wta_2025["tourney_date"].dtype, wta_2025_dates.dt.tz

(['tourney_date'], dtype('int64'), None)

#### 3. What does `tourney_date` mean, and what's the distribution of values?

My takeaways:
- Same as ATP: constant per `tourney_id` for 55/57 tournaments — start-of-week date.
- Exceptions: **WTA Finals** (2 dates) and **BJK Cup** (8 dates) — legitimate, not a bug.
- No per-match date field anywhere in this source.

In [31]:
wta_2025.groupby("tourney_id")["tourney_date"].nunique().value_counts()

tourney_date
1    55
8     1
2     1
Name: count, dtype: int64

In [32]:
wta_date_counts = wta_2025.groupby("tourney_id")["tourney_date"].nunique()
anomalous_tourney_ids = wta_date_counts[wta_date_counts > 1].index

wta_2025[wta_2025["tourney_id"].isin(anomalous_tourney_ids)][
    ["tourney_id", "tourney_name", "tourney_date", "round", "match_num"]
].sort_values(["tourney_id", "tourney_date"])

,tourney_id,tourney_name,tourney_date,round,match_num
2565,2025-808,WTA Finals,20251101,RR,1
2566,2025-808,WTA Finals,20251101,RR,2
2567,2025-808,WTA Finals,20251102,RR,3
2568,2025-808,WTA Finals,20251102,RR,4
2569,2025-808,WTA Finals,20251103,RR,5
2570,2025-808,WTA Finals,20251103,RR,6
2571,2025-808,WTA Finals,20251104,RR,7
2572,2025-808,WTA Finals,20251104,RR,8
2573,2025-808,WTA Finals,20251105,RR,9
2574,2025-808,WTA Finals,20251105,RR,10
2575,2025-808,WTA Finals,20251106,RR,11
2576,2025-808,WTA Finals,20251106,RR,12
2577,2025-808,WTA Finals,20251107,SF,13
2578,2025-808,WTA Finals,20251107,SF,14
2579,2025-808,WTA Finals,20251108,F,15
848,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group B,20250410,RR,7
849,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group B,20250410,RR,8
850,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group B,20250410,RR,9
851,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group B,20250410,RR,10
852,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group B,20250410,RR,11
853,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group B,20250410,RR,12
860,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group D,20250410,RR,19
861,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group D,20250410,RR,20
862,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group D,20250410,RR,21
863,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group D,20250410,RR,22
864,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group D,20250410,RR,23
865,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group D,20250410,RR,24
866,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group E,20250410,RR,25
867,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group E,20250410,RR,26
868,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group E,20250410,RR,27
869,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group E,20250410,RR,28
870,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group E,20250410,RR,29
871,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group E,20250410,RR,30
872,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group F,20250410,RR,31
873,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group F,20250410,RR,32
874,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group F,20250410,RR,33
875,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group F,20250410,RR,34
876,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group F,20250410,RR,35
877,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group F,20250410,RR,36
842,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group A,20250411,RR,1
843,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group A,20250411,RR,2
844,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group A,20250411,RR,3
845,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group A,20250411,RR,4
846,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group A,20250411,RR,5
847,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group A,20250411,RR,6
854,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group C,20250411,RR,13
855,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group C,20250411,RR,14
856,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group C,20250411,RR,15
857,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group C,20250411,RR,16
858,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group C,20250411,RR,17
859,2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group C,20250411,RR,18

In [33]:
atp_2025[atp_2025["tourney_name"].str.contains("Australian Open", case=False)][
    ["tourney_id", "tourney_name", "tourney_date", "round"]
].drop_duplicates(subset=["tourney_id", "tourney_date"])

    tourney_id     tourney_name  tourney_date round
137   2025-580  Australian Open      20250113  R128

#### 4. Does match count per tournament match `draw_size`?

My takeaways:
- 7/57 tourneys mismatched — United Cup and WTA Finals/BJK Cup are known non-standard formats; Washington and Linz traced to the `draw_size` bracket-vs-entrant inconsistency — see questions 7-8.

In [34]:
wta_match_counts = wta_2025.groupby("tourney_id").agg(
    tourney_name=("tourney_name", "first"),
    draw_size=("draw_size", "first"),
    actual_matches=("match_num", "size"),
)
wta_match_counts["expected_matches"] = wta_match_counts["draw_size"] - 1
wta_match_counts["diff"] = (
    wta_match_counts["actual_matches"] - wta_match_counts["expected_matches"]
)

wta_match_counts[wta_match_counts["diff"] != 0]

,tourney_name,draw_size,actual_matches,expected_matches,diff
tourney_id,,,,,
2025-1045,Washington,32,27,31,-4
2025-2084,United Cup,18,25,17,8
2025-528,Linz,32,27,31,-4
2025-808,WTA Finals,8,15,7,8
2025-W-FC-2025-FLS,BJK Cup Finals,8,14,7,7
2025-W-FC-2025-POS,Billie Jean King Cup Play-offs - Group A,3,42,2,40
2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group A,3,36,2,34

#### 5. How do non-standard outcomes (retirement, walkover, default) show up in `score`?

My takeaways:
- 72 distinct patterns — same two categories as ATP: RET (partial set + retirement) and W/O (18). No DEF/ABD.

In [35]:
wta_2025[wta_2025["score"].str.contains(r"[^0-9\-\s()]", na=False)][
    "score"
].value_counts()

score
W/O                18
6-2 1-0 RET         4
7-6(3) RET          3
6-0 RET             3
6-4 2-0 RET         2
                   ..
3-0 RET             1
6-2 2-0 RET         1
6-3 5-0 RET         1
6-3 5-5 RET         1
5-7 6-0 1-0 RET     1
Name: count, Length: 72, dtype: int64

#### 6. Are there duplicate match rows?

My takeaways:
- 0 duplicates, both checks (full-row and business-key) — clean.

In [36]:
wta_2025.duplicated().sum()

np.int64(0)

In [37]:
wta_2025.duplicated(subset=["tourney_id", "winner_name", "loser_name", "round"]).sum()

np.int64(0)

#### 7. Of the tournaments that don't match `draw_size`, which aren't explained by a known special format (Finals/Cup)?

My takeaways:
- Washington and Linz: both short exactly 4 matches, only in `R32` — no `score` anomalies (RET/W/O).
- **Confirmed externally**: both are real **28-draw WTA events** ([Washington](https://www.wtatennis.com/news/4315457/washington-2025-draws-dates-prize-money-and-what-you-need-to-know), [Linz](https://en.wikipedia.org/wiki/2025_Upper_Austria_Ladies_Linz)) — 4 byes for seeds 1-4 is standard for this format, not an anomaly.
- Root cause: `draw_size` mixes two meanings — administrative bracket size (32, here) vs. true entrant count (96 for Madrid, question 8). **`draw_size - 1` isn't a reliable row-count check**; validating round structure is.

In [38]:
wta_mismatches = wta_match_counts[wta_match_counts["diff"] != 0]
known_format = wta_mismatches["tourney_name"].str.contains(
    "Finals|Cup", case=False, na=False
)

wta_mismatches[~known_format]

           tourney_name  draw_size  actual_matches  expected_matches  diff
tourney_id
2025-1045    Washington         32              27                31    -4
2025-528           Linz         32              27                31    -4

In [39]:
washington = wta_2025[wta_2025["tourney_id"] == "2025-1045"]
washington["round"].value_counts()

round
R32    12
R16     8
QF      4
SF      2
F       1
Name: count, dtype: int64

In [40]:
linz = wta_2025[wta_2025["tourney_id"] == "2025-528"]
linz["round"].value_counts()

round
R32    12
R16     8
QF      4
SF      2
F       1
Name: count, dtype: int64

In [41]:
washington[washington["score"].str.contains(r"[^0-9\-\s()]", na=False)][
    ["round", "match_num", "winner_name", "loser_name", "score"]
]

Empty DataFrame
Columns: [round, match_num, winner_name, loser_name, score]
Index: []

In [42]:
linz[linz["score"].str.contains(r"[^0-9\-\s()]", na=False)][
    ["round", "match_num", "winner_name", "loser_name", "score"]
]

Empty DataFrame
Columns: [round, match_num, winner_name, loser_name, score]
Index: []

In [43]:
wta_match_counts.sort_values("diff")

,tourney_name,draw_size,actual_matches,expected_matches,diff
tourney_id,,,,,
2025-1045,Washington,32,27,31,-4
2025-528,Linz,32,27,31,-4
2025-1003,Doha,56,55,55,0
2025-2075,Guadalajara,28,27,27,0
2025-2082,Austin,32,31,31,0
2025-2085,Merida,28,27,27,0
2025-2088,Abu Dhabi,28,27,27,0
2025-2092,Ningbo,28,27,27,0
2025-405,Osaka,32,31,31,0
2025-406,Strasbourg,28,27,27,0
2025-609,Indian Wells,96,95,95,0
2025-709,Rome,96,95,95,0
2025-710,Eastbourne,32,31,31,0
2025-718,Dubai,56,55,55,0
2025-800,Brisbane,48,47,47,0
2025-804,Charleston,48,47,47,0
2025-806,Montreal,96,95,95,0
2025-822,Rosmalen,32,31,31,0
2025-894,Bogota,32,31,31,0
2025-901,Australian Open,128,127,127,0
2025-902,Miami,96,95,95,0
2025-903,Roland Garros,128,127,127,0
2025-904,Wimbledon,128,127,127,0
2025-905,US Open,128,127,127,0
2025-2066,Rouen,32,31,31,0
2025-2050,Cluj-Napoca,32,31,31,0
2025-2063,Iasi,32,31,31,0
2025-2040,Cleveland,32,31,31,0
2025-1005,Rabat,32,31,31,0
2025-1017,Cincinnati,96,95,95,0
2025-1020,Beijing,96,95,95,0
2025-1023,Guangzhou,32,31,31,0
2025-1024,Seoul,28,27,27,0
2025-1038,Madrid,96,95,95,0
2025-1039,Monterrey,28,27,27,0
2025-1049,Auckland,32,31,31,0
2025-1050,Hobart,32,31,31,0
2025-1051,Stuttgart,28,27,27,0
2025-1055,Singapore,32,31,31,0
2025-2042,Hamburg,32,31,31,0
2025-1056,Tokyo,28,27,27,0
2025-1075,Wuhan,56,55,55,0
2025-1077,Jiujiang,32,31,31,0
2025-1080,Nottingham,32,31,31,0
2025-1082,Prague Open,32,31,31,0
2025-1111,Queen's Club,28,27,27,0
2025-1139,Sao Paulo,32,31,31,0
2025-1148,Chennai,32,31,31,0
2025-2012,Berlin,28,27,27,0
2025-2014,Adelaide,30,29,29,0
2025-2017,Bad Homburg,28,27,27,0
2025-1074,Hong Kong,32,31,31,0
2025-W-FC-2025-FLS,BJK Cup Finals,8,14,7,7
2025-808,WTA Finals,8,15,7,8
2025-2084,United Cup,18,25,17,8
2025-W-FC-2025-QUA,Billie Jean King Cup Qualifying Round - Group A,3,36,2,34
2025-W-FC-2025-POS,Billie Jean King Cup Play-offs - Group A,3,42,2,40

#### 8. How do bye cases show up in the data?

My takeaways:
- No explicit "BYE" marker — not in `round`, not in `score`. A bye is a missing row, by omission.
- Confirmed with Sabalenka at Madrid: zero rows before `R64`, 6 matches total.
- Byes only break the row count when `draw_size` isn't the true entrant count (see question 7).

In [44]:
(
    wta_2025["round"].unique(),
    wta_2025[wta_2025["score"].str.contains("bye", case=False, na=False)],
)

(<StringArray>
 ['RR', 'QF', 'SF', 'F', 'R64', 'R32', 'R16', 'R128']
 Length: 8, dtype: str,
 Empty DataFrame
 Columns: [tourney_id, tourney_name, surface, draw_size, tourney_level, indoor, tourney_date, match_num, winner_id, winner_seed, winner_entry, winner_name, winner_hand, winner_ht, winner_ioc, winner_age, winner_rank, winner_rank_points, loser_id, loser_seed, loser_entry, loser_name, loser_hand, loser_ht, loser_ioc, loser_age, loser_rank, loser_rank_points, score, best_of, round, minutes, w_ace, w_df, w_svpt, w_1stIn, w_1stWon, w_2ndWon, w_SvGms, w_bpSaved, w_bpFaced, l_ace, l_df, l_svpt, l_1stIn, l_1stWon, l_2ndWon, l_SvGms, l_bpSaved, l_bpFaced]
 Index: []

 [0 rows x 50 columns])

In [45]:
madrid = wta_2025[wta_2025["tourney_name"].str.contains("Madrid", case=False, na=False)]
madrid["draw_size"].iloc[0], madrid["round"].value_counts()

(np.int64(96),
 round
 R128    32
 R64     32
 R32     16
 R16      8
 QF       4
 SF       2
 F        1
 Name: count, dtype: int64)

In [46]:
madrid[
    (madrid["winner_name"].str.contains("Sabalenka", case=False, na=False))
    | (madrid["loser_name"].str.contains("Sabalenka", case=False, na=False))
][["round", "match_num", "winner_name", "loser_name", "score"]]

     round  match_num      winner_name       loser_name          score
996    R64         61  Aryna Sabalenka    Anna Blinkova        6-3 6-4
1003   R32         68  Aryna Sabalenka    Elise Mertens    3-6 6-2 6-1
1020   R16         85  Aryna Sabalenka   Peyton Stearns        6-2 6-4
1027    QF         92  Aryna Sabalenka    Marta Kostyuk  7-6(4) 7-6(7)
1029    SF         94  Aryna Sabalenka  Elina Svitolina        6-3 7-5
1030     F         95  Aryna Sabalenka       Coco Gauff     6-3 7-6(3)

#### 9. Is the `player_id` ↔ name relationship 1:1?

My takeaways:
- 1 ID violation: `player_id=216133` has two name spellings — "Xinyu Wang" and "Xin Yu Wang" (same player, spacing inconsistency, not the different player "Xiyu Wang"). 0 name violations.
- `player_id` is reliable as a join key regardless — isolated formatting issue, not a real identity conflict.

In [47]:
wta_players = pd.concat(
    [
        wta_2025[["winner_id", "winner_name"]].rename(
            columns={"winner_id": "player_id", "winner_name": "player_name"}
        ),
        wta_2025[["loser_id", "loser_name"]].rename(
            columns={"loser_id": "player_id", "loser_name": "player_name"}
        ),
    ]
).drop_duplicates()

wta_id_violations = wta_players.groupby("player_id")["player_name"].nunique()
wta_id_violations[wta_id_violations > 1]

player_id
216133    2
Name: player_name, dtype: int64

In [48]:
wta_name_violations = wta_players.groupby("player_name")["player_id"].nunique()
wta_name_violations[wta_name_violations > 1]

Series([], Name: player_id, dtype: int64)

In [49]:
wta_players[wta_players["player_id"] == 216133]

     player_id  player_name
328     216133   Xinyu Wang
103     216133  Xin Yu Wang

#### 10. Are the serve-stat columns internally consistent (`1stIn <= svpt`, `1stWon <= 1stIn`, `1stWon + 2ndWon <= svpt`)?

My takeaways:
- 1 violation: Mertens vs. Parrizas Diaz (Hobart R32) — `w_svpt=1`, `l_svpt=3`, but `w_1stIn=104`.
- **Cross-checked against Sofascore (real match stats)**: Mertens actually had `svpt=51, 1stIn=28, 1stWon=22, 2ndWon=13`; Parrizas Diaz `svpt=50, 1stIn=36, 1stWon=16, 2ndWon=9`. Confirmed internally consistent there (`1stWon+2ndWon` = "service points won" exactly, both players). The source's numbers bear no relation to the real match — not a scale or winner/loser swap, just corrupted.
- Combined ATP+WTA: 3 violations out of ~5,566 matches — rare, but exactly the kind of error null/duplicate checks miss. Worth keeping as an ingestion test (#19).

In [50]:
wta_violations = wta_2025[
    (wta_2025["w_1stIn"] > wta_2025["w_svpt"])
    | (wta_2025["w_1stWon"] > wta_2025["w_1stIn"])
    | (wta_2025["w_1stWon"] + wta_2025["w_2ndWon"] > wta_2025["w_svpt"])
    | (wta_2025["l_1stIn"] > wta_2025["l_svpt"])
    | (wta_2025["l_1stWon"] > wta_2025["l_1stIn"])
    | (wta_2025["l_1stWon"] + wta_2025["l_2ndWon"] > wta_2025["l_svpt"])
]

wta_violations[
    [
        "tourney_name",
        "round",
        "winner_name",
        "loser_name",
        "w_svpt",
        "w_1stIn",
        "w_1stWon",
        "w_2ndWon",
        "l_svpt",
        "l_1stIn",
        "l_1stWon",
        "l_2ndWon",
    ]
]

,tourney_name,round,winner_name,loser_name,w_svpt,w_1stIn,w_1stWon,w_2ndWon,l_svpt,l_1stIn,l_1stWon,l_2ndWon
132,Hobart,R32,Elise Mertens,Nuria Parrizas Diaz,1.0,104.0,70.0,42.0,3.0,69.0,38.0,23.0

#### 11. Are break points saved always ≤ break points faced?

My takeaways:
- 1 violation — the same Hobart match from question 10 (Mertens vs. Parrizas Diaz). Confirms that row is broadly corrupted across stat families, not one bad field.

In [51]:
wta_bp_violations = wta_2025[
    (wta_2025["w_bpSaved"] > wta_2025["w_bpFaced"])
    | (wta_2025["l_bpSaved"] > wta_2025["l_bpFaced"])
]

wta_bp_violations[
    [
        "tourney_name",
        "round",
        "winner_name",
        "loser_name",
        "w_bpSaved",
        "w_bpFaced",
        "l_bpSaved",
        "l_bpFaced",
    ]
]

,tourney_name,round,winner_name,loser_name,w_bpSaved,w_bpFaced,l_bpSaved,l_bpFaced
132,Hobart,R32,Elise Mertens,Nuria Parrizas Diaz,13.0,8.0,12.0,4.0

#### 12. Do categorical columns match the values documented in the TML-Database dictionary?

My takeaways:
- `indoor`: same dictionary mismatch as ATP (documented `Yes/No`), moot here since WTA’s `indoor` is 100% null anyway (question on Types and Nulls).
- Same shape as ATP otherwise: `RR` in `round`, `PR`/`ALT` in entry codes, extra `draw_size` values (18, 28, 30, 48, 56, 96, 3) tracing to known non-standard formats (United Cup, 28-draws, Madrid-style, BJK Cup groups).
- `tourney_level` actual values: `250`, `500`, `1000` — same real-tier naming as ATP, but WTA labels its top non-Slam tier `1000` where ATP uses `M`. Same concept, different label per tour — worth normalizing if the two feeds are ever unioned.
- `loser_hand`: `U` (unknown/unrecorded) — sensible real category, just not in the documented `R/L` set.

In [52]:
wta_dict_violations = {
    col: sorted(set(wta_2025[col].dropna().unique()) - allowed, key=str)
    for col, allowed in expected.items()
}
{col: vals for col, vals in wta_dict_violations.items() if vals}

{'draw_size': [np.int64(18),
  np.int64(28),
  np.int64(3),
  np.int64(30),
  np.int64(48),
  np.int64(56),
  np.int64(96)],
 'tourney_level': ['1000', '250', '500'],
 'winner_entry': ['PR'],
 'loser_entry': ['ALT', 'PR'],
 'loser_hand': ['U'],
 'round': ['RR']}

## Historical Consistency

Everything above only profiled 2025. Sampling a few years spread across the full range (1967–2026 ATP, 1990–2026 WTA) to check whether column structure and serve-stat coverage hold up over time — before locking in the raw schema (#16).

### ATP

#### 1. Are columns and serve-stat coverage consistent across sample years?

My takeaways:
- Column structure identical across 1970/1995/2010/2025 — safe to assume a stable ATP schema.
- Serve stats (`w_ace`, `w_svpt`, etc.): **100% null in 1970** (not tracked yet), drops to ~9.6% by 1995. The tracking start is somewhere between those two years, not gradual.
- `winner_rank`/`loser_rank`: also **100% null in 1970** — makes sense, official ATP rankings only began in 1973.
- Both gaps are real historical absence, not ingestion bugs — don't "fix" nulls in pre-1973/pre-1990s rows.

In [53]:
atp_sample_names = ["1970.csv", "1995.csv", "2010.csv", "2025.csv"]
atp_year_dfs = {
    name: (atp_2025 if name == "2025.csv" else pd.read_csv(atp_by_name[name]))
    for name in atp_sample_names
}

atp_columns_match = {
    name: list(df.columns) == list(atp_2025.columns)
    for name, df in atp_year_dfs.items()
}
atp_null_by_year = pd.DataFrame(
    {name: df.isnull().mean() * 100 for name, df in atp_year_dfs.items()}
)

atp_columns_match, atp_null_by_year

({'1970.csv': True, '1995.csv': True, '2010.csv': True, '2025.csv': True},
                       1970.csv   1995.csv   2010.csv   2025.csv
 tourney_id            0.000000   0.000000   0.000000   0.000000
 tourney_name          0.000000   0.000000   0.000000   0.000000
 surface               2.503090   0.000000   0.000000   0.000000
 draw_size             0.000000   0.000000   0.000000   0.543478
 tourney_level         0.000000   0.000000   0.000000   0.000000
 indoor                5.778739   8.605263  10.594059   8.016304
 tourney_date          0.000000   0.000000   0.000000   0.000000
 match_num             0.000000   0.000000   0.000000  16.610054
 winner_id             0.000000   0.000000   0.000000   0.000000
 winner_seed          82.385661  61.394737  57.689769  59.239130
 winner_entry        100.000000  88.921053  89.405941  89.639946
 winner_name           0.000000   0.000000   0.000000   0.000000
 winner_hand           3.800989   0.315789   1.386139   0.611413
 winner_ht            42.150803   2.026316   2.343234   0.951087
 winner_ioc            0.092707   0.000000   0.000000   0.067935
 winner_age            6.118665   0.263158   0.066007   0.067935
 winner_rank         100.000000   1.052632   0.660066   0.441576
 winner_rank_points  100.000000   6.473684   0.660066   0.441576
 loser_id              0.000000   0.000000   0.000000   0.000000
 loser_seed           93.726823  79.289474  77.854785  76.222826
 loser_entry          99.907293  80.342105  79.966997  83.695652
 loser_name            0.000000   0.000000   0.000000   0.000000
 loser_hand           15.729295   0.631579   2.277228   1.698370
 loser_ht             61.063041   4.500000   4.686469   2.105978
 loser_ioc             0.525340   0.000000   0.066007   0.033967
 loser_age            20.519159   1.026316   0.099010   0.101902
 loser_rank          100.000000   2.421053   1.584158   1.970109
 loser_rank_points   100.000000   9.473684   1.584158   1.970109
 score                 0.000000   0.000000   0.000000   0.000000
 best_of               0.000000   0.000000   0.000000   0.000000
 round                 0.000000   0.000000   0.000000   0.000000
 minutes             100.000000  15.842105  11.254125   6.487772
 w_ace               100.000000   9.605263  11.254125   6.555707
 w_df                100.000000   9.605263  11.254125   6.555707
 w_svpt              100.000000   9.605263  11.254125   6.555707
 w_1stIn             100.000000   9.605263  11.254125   6.555707
 w_1stWon            100.000000   9.605263  11.254125   6.555707
 w_2ndWon            100.000000   9.605263  11.254125   6.555707
 w_SvGms             100.000000   9.605263  11.254125   6.555707
 w_bpSaved           100.000000   9.605263  11.254125   6.555707
 w_bpFaced           100.000000   9.605263  11.254125   6.555707
 l_ace               100.000000   9.605263  11.254125   6.555707
 l_df                100.000000   9.605263  11.254125   6.555707
 l_svpt              100.000000   9.605263  11.254125   6.555707
 l_1stIn             100.000000   9.605263  11.254125   6.555707
 l_1stWon            100.000000   9.605263  11.254125   6.555707
 l_2ndWon            100.000000   9.605263  11.254125   6.555707
 l_SvGms             100.000000   9.605263  11.254125   6.555707
 l_bpSaved           100.000000   9.605263  11.254125   6.555707
 l_bpFaced           100.000000   9.605263  11.254125   6.555707)

#### 2. Is the `winner_id`/`loser_id` format stable across sample years?

My takeaways:
- Stable: string/alphanumeric (e.g. `N044`, `K267`, `R485`, `CD85`) in every sampled year. No dtype or pattern drift to worry about in the schema.

In [54]:
{
    name: (df["winner_id"].dtype, df["winner_id"].iloc[0])
    for name, df in atp_year_dfs.items()
}

{'1970.csv': (<StringDtype(storage='python', na_value=nan)>, 'N044'),
 '1995.csv': (<StringDtype(storage='python', na_value=nan)>, 'K267'),
 '2010.csv': (<StringDtype(storage='python', na_value=nan)>, 'R485'),
 '2025.csv': (<StringDtype(storage='python', na_value=nan)>, 'CD85')}

#### 3. Is the `score` format (e.g. tiebreak notation) stable across sample years?

My takeaways:
- Stable enough: tiebreak parenthesis notation present in every sampled year (even 1970, despite the tiebreak being brand new that year), non-standard-score rate stays in a consistent 2-5% band. No major historical drift here.

In [55]:
pd.DataFrame(
    {
        name: {
            "sample_score": df["score"].iloc[0],
            "has_tiebreak_paren": df["score"].str.contains(r"\(", na=False).any(),
            "non_standard_pct": df["score"]
            .str.contains(r"[^0-9\-\s()]", na=False)
            .mean()
            * 100,
        }
        for name, df in atp_year_dfs.items()
    }
).T

         sample_score has_tiebreak_paren non_standard_pct
1970.csv  6-4 3-6 6-2               True         3.430161
1995.csv   7-6(5) 6-1               True         2.210526
2010.csv   7-6(5) 6-2               True         4.026403
2025.csv      6-2 6-1               True           4.6875

#### 4. Is the set of `round` values stable across sample years?

My takeaways:
- Not fully stable: 1970 has two extra values not seen from 1995 onward — `3rd/4th` and `Fs` (an old third-place playoff format that was discontinued). Anything hardcoding "the 8 known round codes" will break on old ATP data.

In [56]:
{name: set(df["round"].unique()) for name, df in atp_year_dfs.items()}

{'1970.csv': {'3rd/4th',
  'F',
  'Fs',
  'QF',
  'R128',
  'R16',
  'R32',
  'R64',
  'RR',
  'SF'},
 '1995.csv': {'F', 'QF', 'R128', 'R16', 'R32', 'R64', 'RR', 'SF'},
 '2010.csv': {'F', 'QF', 'R128', 'R16', 'R32', 'R64', 'RR', 'SF'},
 '2025.csv': {'F', 'QF', 'R128', 'R16', 'R32', 'R64', 'RR', 'SF'}}

### WTA

#### 1. Are columns and serve-stat coverage consistent across sample years?

My takeaways:
- Column structure identical across 1992/2005/2018/2025 — safe to assume a stable WTA schema.
- `indoor` is 100% null in every single sampled year, not just 2025 — confirms it's structurally absent for WTA in this source, not a 2025-specific gap.
- Serve stats: 100% null in 1992, still **80.6% null in 2005**, only well-covered from **2018** onward (~0.8% null). WTA detailed serve stats are only reliable for roughly the last 7-10 years in this source — much later than ATP's ramp-up.

In [57]:
wta_sample_names = ["1992_wta.csv", "2005_wta.csv", "2018_wta.csv", "2025_wta.csv"]
wta_year_dfs = {
    name: (wta_2025 if name == "2025_wta.csv" else pd.read_csv(wta_by_name[name]))
    for name in wta_sample_names
}

wta_columns_match = {
    name: list(df.columns) == list(wta_2025.columns)
    for name, df in wta_year_dfs.items()
}
wta_null_by_year = pd.DataFrame(
    {name: df.isnull().mean() * 100 for name, df in wta_year_dfs.items()}
)

wta_columns_match, wta_null_by_year

({'1992_wta.csv': True,
  '2005_wta.csv': True,
  '2018_wta.csv': True,
  '2025_wta.csv': True},
                     1992_wta.csv  2005_wta.csv  2018_wta.csv  2025_wta.csv
 tourney_id              0.000000      0.000000      0.000000      0.000000
 tourney_name            0.000000      0.000000      0.000000      0.000000
 surface                 0.000000      0.000000      0.000000      0.000000
 draw_size               0.000000      0.000000      0.000000      0.000000
 tourney_level           0.000000      0.000000      0.000000      0.000000
 indoor                100.000000    100.000000    100.000000    100.000000
 tourney_date            0.000000      0.000000      0.000000      0.000000
 match_num               0.000000      0.000000      0.000000      0.000000
 winner_id               0.000000      0.000000      0.000000      0.000000
 winner_seed            53.407821     55.926838     60.123367     61.441648
 winner_entry           92.029795     88.287021     87.119013     83.867277
 winner_name             0.000000      0.000000      0.000000      0.000000
 winner_hand            24.841713      1.547661      2.358491      2.479024
 winner_ht              24.655493      5.029898      5.079826     28.527841
 winner_ioc              0.000000      0.000000      0.000000      0.000000
 winner_age              0.037244      0.000000      0.000000      0.190694
 winner_rank             2.271881      1.829054      1.959361      0.228833
 winner_rank_points      2.271881      1.829054      1.959361      0.228833
 loser_id                0.000000      0.000000      0.000000      0.000000
 loser_seed             79.813780     76.960957     76.923077     74.828375
 loser_entry            83.538175     79.001055     80.442671     76.620900
 loser_name              0.000000      0.000000      0.000000      0.000000
 loser_hand             37.616387      4.220893      4.245283      4.805492
 loser_ht               41.042831      9.848751      8.563135     35.011442
 loser_ioc               0.000000      0.000000      0.000000      0.038139
 loser_age               0.111732      0.000000      0.108853      0.457666
 loser_rank              6.070764      4.291242      3.265602      0.266972
 loser_rank_points       6.070764      4.291242      3.265602      0.266972
 score                   0.000000      0.000000      0.000000      0.000000
 best_of                 0.000000      0.000000      0.000000      0.000000
 round                   0.000000      0.000000      0.000000      0.000000
 minutes               100.000000    100.000000      0.725689     10.144928
 w_ace                 100.000000     80.583890      0.834543      4.118993
 w_df                  100.000000     80.619064      0.834543      4.118993
 w_svpt                100.000000     80.583890      0.834543      4.118993
 w_1stIn               100.000000     80.583890      0.834543      4.118993
 w_1stWon              100.000000     80.583890      0.834543      4.118993
 w_2ndWon              100.000000     80.583890      0.834543      4.118993
 w_SvGms               100.000000    100.000000      0.834543      4.195271
 w_bpSaved             100.000000     80.583890      0.834543      4.118993
 w_bpFaced             100.000000     80.583890      0.834543      4.118993
 l_ace                 100.000000     80.583890      0.834543      4.118993
 l_df                  100.000000     80.619064      0.834543      4.118993
 l_svpt                100.000000     80.583890      0.834543      4.118993
 l_1stIn               100.000000     80.583890      0.834543      4.118993
 l_1stWon              100.000000     80.583890      0.834543      4.118993
 l_2ndWon              100.000000     80.583890      0.834543      4.118993
 l_SvGms               100.000000    100.000000      0.834543      4.195271
 l_bpSaved             100.000000     80.583890      0.834543      4.118993
 l_bpFaced             100.000000     80.583890      0.834543      4.118993)

### WTA

#### 2. Is the `winner_id`/`loser_id` format stable across sample years?

My takeaways:
- Stable: `int64` numeric ID in every sampled year (1992, 2005, 2018, 2025). No dtype drift.

In [58]:
{
    name: (df["winner_id"].dtype, df["winner_id"].iloc[0])
    for name, df in wta_year_dfs.items()
}

{'1992_wta.csv': (dtype('int64'), np.int64(201059)),
 '2005_wta.csv': (dtype('int64'), np.int64(200069)),
 '2018_wta.csv': (dtype('int64'), np.int64(201504)),
 '2025_wta.csv': (dtype('int64'), np.int64(211107))}

#### 3. Is the `score` format (e.g. tiebreak notation) stable across sample years?

My takeaways:
- Stable: tiebreak notation and non-standard-score rate (1.4-3.9%) consistent across all sampled years.

In [59]:
pd.DataFrame(
    {
        name: {
            "sample_score": df["score"].iloc[0],
            "has_tiebreak_paren": df["score"].str.contains(r"\(", na=False).any(),
            "non_standard_pct": df["score"]
            .str.contains(r"[^0-9\-\s()]", na=False)
            .mean()
            * 100,
        }
        for name, df in wta_year_dfs.items()
    }
).T

             sample_score has_tiebreak_paren non_standard_pct
1992_wta.csv      7-5 7-6               True          1.41527
2005_wta.csv      6-2 6-3               True         2.813929
2018_wta.csv  6-4 4-6 6-2               True         3.447025
2025_wta.csv      6-2 6-1               True         3.928299

#### 4. Is the set of `round` values stable across sample years?

My takeaways:
- Stable: same 8 round codes across all sampled years — unlike ATP, no legacy `3rd/4th`/`Fs` values show up here.

In [60]:
{name: set(df["round"].unique()) for name, df in wta_year_dfs.items()}

{'1992_wta.csv': {'F', 'QF', 'R128', 'R16', 'R32', 'R64', 'RR', 'SF'},
 '2005_wta.csv': {'F', 'QF', 'R128', 'R16', 'R32', 'R64', 'RR', 'SF'},
 '2018_wta.csv': {'F', 'QF', 'R128', 'R16', 'R32', 'R64', 'RR', 'SF'},
 '2025_wta.csv': {'F', 'QF', 'R128', 'R16', 'R32', 'R64', 'RR', 'SF'}}

## Understanding Incoming Data

Raised while designing the raw schema (#16): does `<year>.csv` for a season still in progress (2026) only contain matches that have actually finished, or could a still-in-progress match show up before it has a winner? This decides whether a natural key built on `winner_id`/`loser_id` is safe for the files this milestone (#14-#21) actually ingests.

### 1. Is every row in the current-season file a completed match?

My takeaways:
- No unplayed/no-score rows found in `2026.csv` or `2026_wta.csv` — every match that appears has a real score (e.g. `6-4 6-2`), right up to the most recent rows (WTA to 2026-09-21, ATP to 2026-09-20). Consistent with the fetch-scope decision in #14: the truly in-progress matches live in the separately-excluded `*ongoing_tourneys.csv`, not here.
- 1 exception: a WTA Hamburg QF (2026-07-20) has a real winner but a null `score` — an isolated data gap, not an unplayed match (it's 2 months old by the time this ran).
- So for #16's scope, a row existing in `<year>.csv` does mean the match is finished.

In [61]:
atp_2026 = pd.read_csv(atp_by_name["2026.csv"])
wta_2026 = pd.read_csv(wta_by_name["2026_wta.csv"])

current_season_summary = pd.DataFrame(
    {
        "ATP 2026": {
            "rows": len(atp_2026),
            "tourney_date_min": atp_2026["tourney_date"].min(),
            "tourney_date_max": atp_2026["tourney_date"].max(),
            "null_score": atp_2026["score"].isnull().sum(),
            "null_round": atp_2026["round"].isnull().sum(),
        },
        "WTA 2026": {
            "rows": len(wta_2026),
            "tourney_date_min": wta_2026["tourney_date"].min(),
            "tourney_date_max": wta_2026["tourney_date"].max(),
            "null_score": wta_2026["score"].isnull().sum(),
            "null_round": wta_2026["round"].isnull().sum(),
        },
    }
)
current_season_summary

                  ATP 2026  WTA 2026
rows                  2359      2153
tourney_date_min  20260102  20260104
tourney_date_max  20260920  20260921
null_score               0         1
null_round               1         0

In [62]:
# the one null-score row: a real winner, so not an "unplayed" match
wta_2026[wta_2026["score"].isnull()][
    ["tourney_id", "tourney_name", "tourney_date", "round", "winner_name", "loser_name"]
]

,tourney_id,tourney_name,tourney_date,round,winner_name,loser_name
1688,2026-2042,Hamburg,20260720,QF,Elina Avanesyan,Oleksandra Oliynykova

### 2. Are `winner_id`/`loser_id` always populated once a match is finished?

My takeaways:
- No — 6 ATP rows and 74 WTA rows have a finished match (real score, real names) but a missing id on at least one side. Not a "lower-tier event" or "new player" story though: ATP's 6 gaps are always `loser_id` only, and span everything from Davis Cup to Masters 1000 (Miami, Cincinnati) — known tour players, not newcomers. WTA's 74 gaps are mostly both ids null (61/74) and cluster hard in a handful of specific tournaments (Eastbourne, Bad Homburg, 's-Hertogenbosch — all 250/500s), which looks more like a per-tournament source-side gap than a player-level one.
- 1 ATP row (a Davis Cup qualifying tie, Ecuador vs. Australia) also has a null `round`.
- Implication for #16: a natural key built on `winner_id`/`loser_id` will be null for a small slice of current-season rows, unpredictably by tournament rather than by player tier — `winner_name`/`loser_name` are more complete than the ids here, worth factoring into the key design.

In [63]:
atp_missing_ids = atp_2026[
    atp_2026["winner_id"].isnull() | atp_2026["loser_id"].isnull()
]
wta_missing_ids = wta_2026[
    wta_2026["winner_id"].isnull() | wta_2026["loser_id"].isnull()
]

missing_id_counts = pd.Series(
    {"ATP 2026": len(atp_missing_ids), "WTA 2026": len(wta_missing_ids)},
    name="rows_missing_winner_id_or_loser_id",
)
missing_id_counts

ATP 2026     6
WTA 2026    74
Name: rows_missing_winner_id_or_loser_id, dtype: int64

In [64]:
atp_missing_ids[
    [
        "tourney_id",
        "tourney_name",
        "round",
        "winner_id",
        "winner_name",
        "loser_id",
        "loser_name",
    ]
]

,tourney_id,tourney_name,round,winner_id,winner_name,loser_id,loser_name
785,2026-403,Miami Masters,R64,HB64,Quentin Halys,NaN,Alejandro Davidovich Fokina
1759,2026-316,Bastad,R16,B0BI,Sebastian Baez,NaN,Jesper De Jong
1794,2026-319,Kitzbuhel,R32,SL28,Jan-Lennard Struff,NaN,Aleksandr Shevchenko
2007,2026-422,Cincinnati Masters,R128,M0QI,Alex Michelsen,NaN,Jesper De Jong
2010,2026-422,Cincinnati Masters,R128,V812,Botic Van De Zandschulp,NaN,Aleksandr Shevchenko
2349,2026-M-DC-2026-WG2-R1-MAR-NGR-01,Davis Cup WG2 R1: MAR vs NGR,RR,D0FA,Yassine Dlimi,NaN,Abubakar Yusuf

In [65]:
atp_2026[atp_2026["round"].isnull()][
    ["tourney_id", "tourney_name", "tourney_date", "winner_name", "loser_name", "score"]
]

,tourney_id,tourney_name,tourney_date,winner_name,loser_name,score
331,2026-M-DC-2026-QLS-M-ECU-AUS-01,Davis Cup QLS R1: ECU vs AUS,20260206,Jason Kubler,Emilio Camacho,6-4 6-2

### 3. Is `tourney_id` unique to one tournament? Is `match_num` unique within it?

My takeaways:
- **`tourney_id` collision, real bug**: `2026-416` holds 1 row for Munich (13 Apr) and the entire 95-match Rome Masters draw (6-17 May) — different city, different dates, same id. 0 such collisions in ATP/WTA 2025 or ATP 2026 otherwise — looks like an isolated glitch in this one live-season id, not systemic.
- **`tourney_id` sharing, but structural, not a bug**: WTA 2025 has 2 ids each covering several distinct group-stage "tourney_name"s — `2025-W-FC-2025-POS` spans Billie Jean King Cup Play-offs Groups A-G, `2025-W-FC-2025-QUA` spans Qualifying Round Groups A-F. Consistent with the known BJK Cup team-event pattern from #14 (multiple dates per tourney_id) — the source seems to key BJK Cup by *phase*, not by group, so grouping there is intentional, unlike Munich/Rome.
- **`match_num` duplicate, real bug**: `2026-422` (Cincinnati Masters) has two distinct real matches both numbered 79 (R32) — numbering skips 80 and repeats 79. 0 such real duplicates found elsewhere (ATP/WTA 2025, WTA 2026) once null `match_num` rows are excluded from the check (see the fixed helper below — first pass wrongly counted 489 null-vs-null "duplicates" in ATP 2025 before the fix).
- Net: both `tourney_id` and `match_num` glitches found so far look like rare, isolated data bugs rather than a recurring pattern, plus one structural case (BJK Cup) that isn't a bug at all. Worth sampling a few more years before concluding it's *always* rare.

In [66]:
def tourney_id_collisions(df):
    """Return rows where the same tourney_id maps to more than one tourney_name."""
    name_counts = df.groupby("tourney_id")["tourney_name"].nunique()
    collided_ids = name_counts[name_counts > 1].index
    return (
        df[df["tourney_id"].isin(collided_ids)][
            ["tourney_id", "tourney_name", "tourney_date"]
        ]
        .drop_duplicates()
        .sort_values("tourney_id")
    )


pd.concat(
    {
        "ATP 2026": tourney_id_collisions(atp_2026),
        "WTA 2026": tourney_id_collisions(wta_2026),
    },
    names=["tour"],
)

              tourney_id  tourney_name  tourney_date
tour
ATP 2026 967    2026-416        Munich      20260413
         1124   2026-416  Rome Masters      20260506
         1137   2026-416  Rome Masters      20260507
         1156   2026-416  Rome Masters      20260508
         1170   2026-416  Rome Masters      20260509
         1187   2026-416  Rome Masters      20260510
         1196   2026-416  Rome Masters      20260511
         1204   2026-416  Rome Masters      20260512
         1212   2026-416  Rome Masters      20260513
         1213   2026-416  Rome Masters      20260514
         1216   2026-416  Rome Masters      20260515
         1217   2026-416  Rome Masters      20260516
         1218   2026-416  Rome Masters      20260517

In [67]:
def match_num_real_duplicates(df):
    """Same (tourney_id, match_num) but different players -- a numbering bug, not a row duplicate."""
    populated = df.dropna(subset=["match_num"])
    dupes = populated[
        populated.duplicated(subset=["tourney_id", "match_num"], keep=False)
    ]
    return dupes[
        ~dupes.duplicated(
            subset=["tourney_id", "match_num", "winner_name", "loser_name"], keep=False
        )
    ]


pd.concat(
    {
        "ATP 2026": match_num_real_duplicates(atp_2026),
        "WTA 2026": match_num_real_duplicates(wta_2026),
    },
    names=["tour"],
)[["tourney_id", "tourney_name", "round", "match_num", "winner_name", "loser_name"]]

              tourney_id        tourney_name round  match_num  \
tour
ATP 2026 967    2026-416              Munich   R32          1
         1124   2026-416        Rome Masters  R128          1
         2068   2026-422  Cincinnati Masters   R32         79
         2069   2026-422  Cincinnati Masters   R32         79

                           winner_name        loser_name
tour
ATP 2026 967               Ben Shelton       Emilio Nava
         1124  Botic Van De Zandschulp  Alexandre Muller
         2068           Frances Tiafoe      Learner Tien
         2069    Christopher O'Connell      Joao Fonseca

Same two checks against a closed year (2025), to see if this is a live-data-still-settling thing or shows up in finalized data too.

In [68]:
pd.concat(
    {
        "ATP 2025": tourney_id_collisions(atp_2025),
        "WTA 2025": tourney_id_collisions(wta_2025),
    },
    names=["tour"],
)

                       tourney_id  \
tour
WTA 2025 2580  2025-W-FC-2025-POS
         2586  2025-W-FC-2025-POS
         2592  2025-W-FC-2025-POS
         2598  2025-W-FC-2025-POS
         2604  2025-W-FC-2025-POS
         2610  2025-W-FC-2025-POS
         2616  2025-W-FC-2025-POS
         842   2025-W-FC-2025-QUA
         848   2025-W-FC-2025-QUA
         854   2025-W-FC-2025-QUA
         860   2025-W-FC-2025-QUA
         866   2025-W-FC-2025-QUA
         872   2025-W-FC-2025-QUA

                                                  tourney_name  tourney_date
tour
WTA 2025 2580         Billie Jean King Cup Play-offs - Group A      20251114
         2586         Billie Jean King Cup Play-offs - Group B      20251114
         2592         Billie Jean King Cup Play-offs - Group C      20251114
         2598         Billie Jean King Cup Play-offs - Group D      20251114
         2604         Billie Jean King Cup Play-offs - Group E      20251114
         2610         Billie Jean King Cup Play-offs - Group F      20251114
         2616         Billie Jean King Cup Play-offs - Group G      20251114
         842   Billie Jean King Cup Qualifying Round - Group A      20250411
         848   Billie Jean King Cup Qualifying Round - Group B      20250410
         854   Billie Jean King Cup Qualifying Round - Group C      20250411
         860   Billie Jean King Cup Qualifying Round - Group D      20250410
         866   Billie Jean King Cup Qualifying Round - Group E      20250410
         872   Billie Jean King Cup Qualifying Round - Group F      20250410

In [69]:
pd.concat(
    {
        "ATP 2025": match_num_real_duplicates(atp_2025),
        "WTA 2025": match_num_real_duplicates(wta_2025),
    },
    names=["tour"],
)[["tourney_id", "tourney_name", "round", "match_num", "winner_name", "loser_name"]]

Empty DataFrame
Columns: [tourney_id, tourney_name, round, match_num, winner_name, loser_name]
Index: []